language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install sass
- gem install compass
- npm install -g bower grunt-cli
- bower install
before_deploy: "grunt build"
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJLDXXQGNDUKUM3PA
  secret_access_key:
    secure: be8QYDpvQYphDTL+G5WCsVjvVxHUtL+kG0UQRJwDkirMiU7AgZGmbnzoHQpZ+xpFjUp2BpHeni9tYRDwG/Q1cTwMcbWFslDqoZOTziMRN/H95/RyB6nJ+aJR4qgwVlV908UEODLVnPzbEeestlxse67KGCEd1JAlBQNFNhy8+tc=
  bucket: proxmate.me
  local-dir: dist
  on:
    repo: dabido/proxmate.me
    branch: master